---
name: version-AlphaBeta
version: 0.05
author:
  - 'John Peacock, E<lt>jpeacock@cpan.orgE<gt>'
abstract: Use alphanumeric version objects
license: perl
requires:
  version: 0.32
provides:
  version::AlphaBeta:
    file: lib/version/AlphaBeta.pm
    version: 0.05
generated_by: Module::Build version 0.2701
